### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by edouardkleinhans** [linuxserver/docker-rutorrent#12]
Hello, I can't upload file from the GUI.

open() "/var/lib/nginx/tmp/client_body/0000000002" failed (13: Permission denied), client: 172.17.0.2, 
server: _, request: "POST /php/addtorrent.php? HTTP/1.1", 

Is it normal that "users" and "abc" have the same group id ?

cat /etc/group
root:x:0:root
bin:x:1:root,bin,daemon
daemon:x:2:root,bin,daemon
...
...
users:x:1000:games,abc
...
...
abc:!:1000:
...
...

**Comment by sparklyballs** [comment]
can you make sure you have the latest version of the image, as this should be fixed in the later version.
make sure you know your docker run command, then issue

`docker stop <container-name> && docker rm <container-name>`

followed by

`docker pull linuxserver/rutorrent`

and finally your run command again.

**Comment by edouardkleinhans** [comment]
I already have the latest image 
linuxserver/rutorrent                    latest              d0f3b31eaceb        5 days ago          119.5 MB

and same error again.

Is it normal that "users" and "abc" have the same group id ?

**Comment by j0nnymoe** [comment]
could you post the command you are using to start this docker please?

Thanks

**Comment by edouardkleinhans** [comment]
still have an error.

This is my docker-compose file 

rutorrent:
  ports:
- 45566:45566/tcp
  environment:
    PGID: '1000'
    PUID: '1000'
  labels:
    io.rancher.container.pull_image: always
  image: linuxserver/rutorrent
  volumes:
- /home/docker/rutorrent/config:/config
- /home/seedbox/finished:/downloads/finished
- /home/seedbox/watch:/downloads/watch

**Comment by adampetrovic** [comment]
I also have this issue. It is happening when SickBeard tries to add a new torrent via the /plugins/httprpc/action.php endpoint of rutorrent.

Looking in the nginx error logs, this line is there:

`2016/09/21 07:57:51 [crit] 249#0: *660 open() "/var/lib/nginx/tmp/client_body/0000000002" failed (13: Permission denied), client: 172.17.0.1, server: _, request: "POST /plugins/httprpc/action.php HTTP/1.1", host: "192.168.200.5:8080"`

**Comment by denkristoffer** [comment]
This problem went away for me after pulling the latest image and starting over with an empty config directory.

**Comment by edouardkleinhans** [comment]
I'm using htpasswd like on my nginx reverse proxy in front of rutorrent container. So my user in /config/rutorrent/profiles/users is not abc.

Does it matter ?

**Comment by DinCahill** [comment]
I'm getting this issue on my Ubuntu Server 14.04 machine, and I haven't been able to fix it. I'm using the latest image.

However, it works fine on the ubuntu/trusty64 Vagrant box (via VirtualBox). My server's installation has probably got a bit out of hand, so I might have to reinstall it, and make more use of containers and VMs in future, to keep the host clean!

**Comment by j0nnymoe** [comment]
@edouardkleinhans is this still an issue for you? looking at your compose file, is /home/seedbox a remote mount? as if it is, it could be down to the permissions of that mount rather than the docker.

**Comment by ghost** [comment]
Same problem here... Let me know whats needed to help troubleshoot.

**Comment by j0nnymoe** [comment]
@ir0noxide Hey, can you let us know some specifics about your setup, host server / docker run command etc then we can look into this further. Thanks

**Comment by ghost** [comment]
@j0nnymoe pretty straightforward installation - only difference is that Im using the `jwilder/nginx-proxy` container as a reverse proxy.

My compose file:

```
version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    restart: always

  rutorrent:
    image: linuxserver/rutorrent
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: '<redacted>'
      VIRTUAL_PORT: 80
    networks:
      - internal
    ports:
      - "51413:51413"
      - "6881:6881/udp"
    volumes:
      - ./rutorrent:/config
      - ./files:/downloads
    restart: always

networks:
  internal:
    driver: bridge
```

It may be worth mentioning that when this starts, a simple `docker-compose restart` makes things work again. This leads me to believe that some process is changing the perm on something in that folder structure after the containers been running for a bit.

**Comment by sparklyballs** [comment]
closing this

**Comment by prior-l** [comment]
I ran 
`ls -l /usr/share/webapps/rutorrent/conf`
and all the files had --------- for permissions so I ran 
`chmod 755 /usr/share/webapps/rutorrent/conf/*`
and that fixed the problem for me

**Comment by albertusQuelle** [comment]
I am using the latest one and still have the permission error
